### ISSUE TITLE
PR not created anymore when sending PullRequestGitHubInteraction message

### ISSUE THREAD

**Issue by vincent-fuchs** [societe-generale/ci-droid-tasks-consumer#13]
## Summary

When sending below action, branch is created, but not the PR : 

```yml
{
  "gitLogin": "vincent-fuchs",
  "gitHubOauthToken": "XXXXXXXXXXXXXX",
  "email": "vincent.fuchs@domain.com",
  "commitMessage": "removing maven-source-plugin",

  "updateAction": {
    "@class": "com.societegenerale.cidroid.extensions.actionToReplicate.RemoveMavenDependencyOrPluginAction",
    "artifactId": "maven-source-plugin"
  },

  "gitHubInteractionType": {
    "@c": ".PullRequestGitHubInteraction",
    "branchNameToCreate": "removingMavenSourcePlugin"
  },
  "resourcesToUpdate": [
    {"repoFullName": "myOrga/myRepo","filePathOnRepo": "pom.xml","branchName": "master"}
  ]
}
```

No error in logs either..

## Type of Issue

It is a : 
 - [ X] bug

## Expected Behavior

PR should be created

## Your Environment

* Version used: 1.0.4
